import {
	ChatConversation,
	Copilot,
	CopilotCheckpoint,
	CopilotCheckpointWrites,
	CopilotKnowledge,
	CopilotOrganization,
	CopilotUser,
	Knowledgebase,
	KnowledgeDocument,
	Xpert,
	XpertAgent,
	XpertRole,
	XpertTool,
	XpertToolset,
	XpertWorkspace,
} from './internal'

export const ALL_AI_ENTITIES = [
	Copilot,
	CopilotKnowledge,
	CopilotOrganization,
	CopilotUser,
	CopilotCheckpoint,
	CopilotCheckpointWrites,
	Knowledgebase,
	KnowledgeDocument,
	ChatConversation,
	Xpert,
	XpertAgent,
	XpertRole,
	XpertTool,
	XpertToolset,
	XpertWorkspace,
]
