import {
	ChatConversation,
	Copilot,
	CopilotModel,
	CopilotCheckpoint,
	CopilotCheckpointWrites,
	CopilotKnowledge,
	CopilotOrganization,
	CopilotUser,
	CopilotProvider,
	CopilotProviderModel,
	Knowledgebase,
	KnowledgeDocument,
	Xpert,
	XpertAgent,
	XpertTool,
	XpertToolset,
	XpertWorkspace,
	XpertAgentExecution,
} from './internal'

export const ALL_AI_ENTITIES = [
	Copilot,
	CopilotModel,
	CopilotKnowledge,
	CopilotOrganization,
	CopilotUser,
	CopilotCheckpoint,
	CopilotCheckpointWrites,
	CopilotProvider,
	CopilotProviderModel,
	Knowledgebase,
	KnowledgeDocument,
	ChatConversation,
	Xpert,
	XpertAgent,
	XpertTool,
	XpertToolset,
	XpertWorkspace,
	XpertAgentExecution
]
