export enum AnalyticsFeatures {
	/**
	 * @deprecated use FEATURE_BUSINESS_AREA
	 */
	FEATURE_BUSINESS_GROUP = 'FEATURE_BUSINESS_GROUP',
	
	FEATURE_BUSINESS_AREA = 'FEATURE_BUSINESS_AREA',
	FEATURE_INDICATOR = 'FEATURE_INDICATOR',
	FEATURE_INDICATOR_MARKET = 'FEATURE_INDICATOR_MARKET',
	FEATURE_INDICATOR_REGISTER = 'FEATURE_INDICATOR_REGISTER',
	FEATURE_INDICATOR_MY = 'FEATURE_INDICATOR_MY',
	FEATURE_INDICATOR_VIEWER = 'FEATURE_INDICATOR_VIEWER',
	FEATURE_STORY = 'FEATURE_STORY',
	FEATURE_STORY_CREATION = 'FEATURE_STORY_CREATION',
	FEATURE_STORY_VIEWER = 'FEATURE_STORY_VIEWER',
	FEATURE_STORY_MARKET = 'FEATURE_STORY_MARKET',
	FEATURE_MODEL = 'FEATURE_MODEL',
	FEATURE_MODEL_CREATION = 'FEATURE_MODEL_CREATION',
	FEATURE_MODEL_VIEWER = 'FEATURE_MODEL_VIEWER',
	FEATURE_SUBSCRIPTION = 'FEATURE_SUBSCRIPTION',
	FEATURE_INSIGHT = 'FEATURE_INSIGHT',
	FEATURE_INSIGHT_ADMIN = 'FEATURE_INSIGHT_ADMIN',
	FEATURE_INSIGHT_VIEWER = 'FEATURE_INSIGHT_VIEWER',
}