export enum IntrinsicMemberProperties {
    Unkown,
    CATALOG_NAME,
    DESCRIPTION,
    PARENT_UNIQUE_NAME,
    MEMBER_UNIQUE_NAME,
    MEMBER_CAPTION,
    MEMBER_TYPE,
    LEVEL_NUMBER,
    CHILDREN_CARDINALITY,
    MEMBER_ORDINAL
}
