import { API_PREFIX } from '@metad/cloud/state'
export const API_VISITS = API_PREFIX + '/visits'
export const API_FEEDS = API_PREFIX + '/feeds'
export const API_COPILOT_KNOWLEDGE = API_PREFIX + '/copilot-knowledge'
export const API_COPILOT_ROLE = API_PREFIX + '/copilot-role'
export const API_COPILOT_MODEL = API_PREFIX + '/copilot-model'
export const API_XPERT_ROLE = API_PREFIX + '/xpert'
export const API_XPERT_TOOLSET = API_PREFIX + '/xpert-toolset'
export const API_XPERT_TOOL = API_PREFIX + '/xpert-tool'
export const API_XPERT_WORKSPACE = API_PREFIX + '/xpert-workspace'
export const API_COPILOT_USER = API_PREFIX + '/copilot-user'
export const API_COPILOT_ORGANIZATION = API_PREFIX + '/copilot-organization'
export const API_COPILOT_CHECKPOINT = API_PREFIX + '/copilot-checkpoint'
