import { API_PREFIX } from '@metad/cloud/state'
export const API_VISITS = API_PREFIX + '/visits'
export const API_FEEDS = API_PREFIX + '/feeds'
export const API_COPILOT_KNOWLEDGE = API_PREFIX + '/copilot-knowledge'
export const API_COPILOT_ROLE = API_PREFIX + '/copilot-role'
